name: Build and Test with Cucumber and JaCoCo

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Set up JDK 17
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: "temurin" # You can use 'zulu' or 'adopt' as well
          java-version: "18"

      # Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      # Navigate to coffee-machine directory and build with Maven
      - name: Build with Maven
        run: |
          cd coffee-machine
          mvn clean verify

      # Publish JaCoCo Coverage Report
      - name: Publish JaCoCo Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: jacoco-report
          path: coffee-machine/target/site/jacoco/index.html

      # Run Cucumber Tests
      - name: Run Cucumber Tests
        run: |
          cd coffee-machine
          mvn exec:java -Dcucumber.options="--plugin pretty --plugin html:target/cucumber-reports/cucumber.html"

      # Upload Cucumber HTML report
      - name: Upload Cucumber Report
        uses: actions/upload-artifact@v3
        with:
          name: cucumber-report
          path: coffee-machine/target/cucumber-reports/cucumber.html
